### ISSUE TITLE
401, Auth Error

### ISSUE THREAD

**Issue by edprats** [davidpett/ember-data-contentful#10]
Hey there, I'm using the add-on and I keep getting 401 "AccessTokenInvalid" errors. Is there a way you could put up the demo ember app on the github, just for reference? I want to make sure I have everything mapped correctly (model/post and config.js).

Thanks!

**Comment by davidpett** [comment]
It's in the tests/dummy dir https://github.com/davidpett/ember-data-contentful/tree/master/tests/dummy
