### ISSUE TITLE
Support for retrieval of linked items

### ISSUE THREAD

**Issue by simonexmachina** [davidpett/ember-data-contentful#14]
Would it be possible and easy or hard to support [retreival of linked items](https://www.contentful.com/developers/docs/concepts/links/#linked-entries)?

**Comment by simonexmachina** [comment]
I can see there's code in the serializer to handle `payload.includes`, but it's not clear how I should indicate to the adapter that they should be included.

**Comment by simonexmachina** [comment]
I can see that the assets are being included in the response, but it looks to me that the serializer `_normalizeResponse` method is expecting the call to `this.normalize()` to return and object with `data` and `included`, but this only returns `data`.

However `data.relationships` does contain the included assets from the response.

**Comment by davidpett** [comment]
@aexmachina sorry, been very busy lately. Referenced items are included by default to help with rate limits from contentful, and are accessible if your ember model has a relationship defined. If you have a different use case then this, please let me know (maybe a demo app?) and we can work on the solution. Thanks

**Comment by simonexmachina** [comment]
Thanks. Hmmn, that wasn't working for me. Maybe I was doing it wrong. I've already changed to using the Contentful lib directly because I didn't need the ember-data functionality.
