### ISSUE TITLE
CamelCase Content Models?

### ISSUE THREAD

**Issue by allthesignals** [davidpett/ember-data-contentful#17]
Great add-on, thanks for working on this. 

If I have a Contentful model such as "TopicArea", I'm not sure how to get Ember to query it correctly. I tried using `pathForType` to set it, but maybe I'm missing something. Any thoughts?

Thank you!

**Comment by davidpett** [comment]
Although you can TitleCase your content model in Contentful, When you create the model, it automatically sets the API identifier to camelCase. Ember uses camelCase when getting the model name, which is how I am requesting the Contentful model: https://github.com/davidpett/ember-data-contentful/blob/master/addon/adapters/contentful.js#L106

**Comment by vinnyatanasov** [comment]
@davidpett We're seeing the request use the kebab case model name, not the camelCase model name.

We have a model name of "blogPost" in contentful, but when we do 

```javascript
model() {
    return this.store.findAll('blogPost');
  }
```

the url it creates is `https://cdn.contentful.com/spaces/s0m3th1ng/entries/?content_type=blog-post&access_token=s0m3th1ng`

but from what you're saying about, it should be requesting `https://cdn.contentful.com/spaces/s0m3th1ng/entries/?content_type=blogPost&access_token=s0m3th1ng`

right?

**Comment by davidpett** [comment]
@vinnyatanasov I misspoke, the `model.modelName` property is lowercase and dasheirzed: http://emberjs.com/api/data/classes/DS.Model.html#property_modelName It seems like I have stayed with that convention when I create content types in contentful.

I assume we can add a configuration to set the style of that `modelName` property.

Do either of you want to take a crack at it?

**Comment by allthesignals** [comment]
Thanks, @davidpett, I can look this weekend. @vinnyatanasov thanks for articulating the issue better than I did.

**Comment by morganick** [comment]
@allthesignals @vinnyatanasov will this work for you: https://github.com/davidpett/ember-data-contentful/pull/18

I ran into the same issue. This should allow you to make the API identifier whatever you want inside of Contentful and then matching it per adapter inside your app. This is also helpful when you weren't the person that created the content models and have to live with what's there.

As stated in the PR, I'm not sold on the name of the method let me know if there is something better you guys can think of.

**Comment by davidpett** [comment]
PR merged, waiting for another one before cutting a new release.
