### ISSUE TITLE
Includes not loaded when using `queryRecord`

### ISSUE THREAD

**Issue by morganick** [davidpett/ember-data-contentful#20]
When you query a single record, it doesn't load any of the included records because they are not part of the mutated payload that's passed along:

https://github.com/davidpett/ember-data-contentful/blob/master/addon/serializers/contentful.js#L111

Before I make this change and a subsequent change inside of: https://github.com/davidpett/ember-data-contentful/blob/master/addon/serializers/contentful.js#L143

I would like to add some tests to the add-on specifically around what I'm about to _break_ so we can have some confidence in the changes I'm making.

One thing that I've found really difficult is getting unit tests setup for the serializer; simply because the serializer uses the `this.store` inside of `extractRelationship`. (This is something that I've noticed inside of `ember-data` proper and they have an entire helpers folder dedicated to getting the world (state) setup.)

I'm not quite sure how to approach this. On the one hand we should have a unit test; however, the state needed to do it would be available to us inside of a functional (acceptance) test that uses the dummy app inside the test directory.

I'm a bit new to the JS testing scene, especially inside of an add-on, so I'll continue to read up and see what I can do. Any suggestions?

**Comment by davidpett** [comment]
I see a flaw in how it is setup right now. It should have a common `_extractIncludes` method that is used in both the single response and the array response.

I've not tested a serializer before (obvious lack of tests here), so I'm not the one to give guidance. Any change here shouldn't break backwards compat as long as there is a single object returned when the queryRecord is called.

If this is something that you have time to tackle, please be my guest. I will possibly have some time to help out soon too. You can always hit me up in the ember slack too.

**Comment by morganick** [comment]
The beginning https://github.com/davidpett/ember-data-contentful/pull/21
