### ISSUE TITLE
Error while processing route: index Could not find module `fetch` imported from `ember-data-contentful/adapters/contentful` Error: Could not find module `fetch` imported from `ember-data-contentful/adapters/contentful`

### ISSUE THREAD

**Issue by Pieter-Rees** [davidpett/ember-data-contentful#35]
I did a reinstall of my project with ember-data-contentfull. When i spin up my application it won't start. The error in my console is: Error while processing route: index Could not find module `fetch` imported from `ember-data-contentful/adapters/contentful` Error: Could not find module `fetch` imported from `ember-data-contentful/adapters/contentful`.
When i remove  
```
model() {
  return this.store.findAll('x');
},
```
It works again. How can i solve this problem? Did i miss something?

**Comment by jonnygreen** [comment]
@Pieter-Rees v0.2.4 switched from the deprecated [ember-network](https://github.com/tomdale/ember-network) to use [ember-fetch](https://github.com/ember-cli/ember-fetch), which I think is the source of this error, though if installed correctly, ember-fetch will also install. It looks like it hasn't in your case.

One solution would be just to install ember-fetch separately:

* `ember install ember-fetch`

though I'm curious why it didn't install as part of the add-on. When you say:

> I did a reinstall of my project with ember-data-contentful

How did you do the reinstall? Did you definitely run `yarn` or `npm install` after?

**Comment by Pieter-Rees** [comment]
Yes, i removed my node_modules and did a npm install. After that didn't work i tried to remove my package-lock.json and then did a fresh install. It didn't work either.

Oh and by the way, your solution works. Thanks!
