### ISSUE TITLE
Meta object from response is empty

### ISSUE THREAD

**Issue by DanielOchoa** [davidpett/ember-data-contentful#7]
The meta object from a response is missing fields such as `limit`, `skip` and `total` that are available as part of contentful's response. I haven't looked into the codebase so is there any way to get that metadata right now? If not, I may submit a PR sometime later.

**Comment by DanielOchoa** [comment]
WIP => https://github.com/DanielOchoa/ember-data-contentful/commit/e8d643017a8cbfe9b633c4f60ac120755efc85aa

Edit: It works, as soon as I add tests I'll submit a PR.

**Comment by davidpett** [comment]
Awesome, thanks! and you can add as many tests as you want (see https://github.com/davidpett/ember-data-contentful/issues/1) ;)

**Comment by DanielOchoa** [comment]
Sounds good!

**Comment by RobbieTheWagner** [comment]
@DanielOchoa what's the status on this? It's been awhile since this was updated.

**Comment by DanielOchoa** [comment]
I completely forgot about this. I'll jump back on it sometime this week.

**Comment by RobbieTheWagner** [comment]
Thanks @DanielOchoa! Do you guys find contentful is easy for your clients to use to edit their own site content? I'm exploring options of what CMS type things work nicely with Ember.

**Comment by DanielOchoa** [comment]
I wouldn't be able to say.. I had to use it briefly to consume some content but I haven't played with doing edits yet.
